### PR TITLE
gemmer-listing

### PR DESCRIPTION
**Pull request by padenmoss**
List Vertcoin on Gemmer 💎

### CODE REVIEW

**Comment by padenmoss** [comment]
Does this need to end in .md to be merged?

**Comment by vertiond** [comment]
The way this works is that proposals are made by those wishing to do work in return for payment.  It appears that this is an attempt to raise awareness about completing a listing process. Something like this should be mentioned to the various communities. If there is any interest, this will be trivial for someone to complete.

**Comment by vertiond** [comment]
List of vertcoin communities: https://vertcoin.org/community

**Comment by vertiond** [comment]
Suggested communities to forward this to would be Reddit (r/vertcoin), Discord, Telegram. https://vertcoin.org/community

**Pull request closed without merging**
